<h3>TODO</h3>
<ul>
	<li>Commencer une doc pr #1 mvc (prise en main), #2 lib js(prise en main)... Voir l'api plus tard</li>
	<li>Permettre à l'utilisateur de configurer sa connexion au sgbdr</li>
	<li>Creer un helper Ajax</li>
	<li>Revoir la class Ajax.js</li>
	<li>Crossbrowser pour la lib js</li>
	<li>Implementer des drivers de connexion: MSSQL, PGSQL, ORACLE</li>
	<li>Mettre en cache la structure de la bdd ou ajouter des requetes prépare || fcts</li>
	<li>Ajouter le chargement de fichier text/plain text/xml text/ini a la class registry</li>
	<li>Gerer l'i18n</li>
	<li>Gerer les logs SQL (requetes)</li>
	<li>hide/show databases</li>
	<li>Implementer IDAO sur le model</li>
	<li>Revoir la conception du "framework"</li>
	<li>gerer une sorte de populate de la db</li>
	<li>gerer une sorte de mailing list a travers l'interface de gestion de bdd</li>
</ul>