<!-- MENU TABLE -->
<?php if (isset($db_selected)): ?>
<ul class="menu_tab">
	<li><?php echo $db_selected; ?></li>
	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'list'), 'structure'); ?></li>
	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'visualization'), 'visualisation'); ?></li>
	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'export'), 'exporter'); ?></li>
	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'import'), 'importer'); ?></li>
</ul>
<?php endif; ?>
