<div id="breadcrumb">
    <h2>Todo &gt; </h2>
    <h3>Index</h3>
</div>
<?php if (isset($confirmation)): ?>
<h4 class="<?php echo $confirmation['state'] ? "success" : "error"; ?>"><?php echo $confirmation['message'] ?></h4>
<?php endif; ?>

<table>
	<caption>Todo list</caption>
	<thead>
    	<tr>
        	<th>Titre</th>
        	<th>Avancement</th>
        	<th>Created</th>
        	<th>Action</th>
    	</tr>
    </thead>
    <tbody>
        <?php foreach ($todo_list as $todo_item): ?>
    	<tr>
    		<td><?php echo $todo_item['titre']; ?></td>
    		<td><?php echo $todo_item['avancement']; ?></td>
    		<td><?php echo $todo_item['created']; ?></td>
    		<td>
    		    <?php echo $html->link(array('action' => 'update', 'params' => array('id' =>  $todo_item['id'])), 'Modifier'); ?>
    		    <?php echo $html->link(array('action' => 'delete', 'params' => array('id' =>  $todo_item['id'])), 'Supprimer'); ?>
    		    <?php echo $html->link(array('action' => 'read', 'params' => array('id' =>  $todo_item['id'])), 'Voir'); ?>
    		</td>
    	</tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
    	<tr>
    		<td colspan="7" align="right"><?php echo $html->link(array('action' => 'create'), 'Ajouter'); ?></td>
    	</tr>
    </tfoot>
</table>