<div id="breadcrumb">
    <h2>Todo &gt; </h2>
    <h3>Read</h3>
</div>
<p><strong>id :</strong><?php echo $todo_item['id']; ?></p>
<p><strong>titre :</strong><?php echo $todo_item['titre']; ?></p>
<p><strong>rappel :</strong><?php echo $todo_item['rappel']; ?></p>
<p><strong>avancement :</strong><?php echo $todo_item['avancement']; ?></p>
<p><strong>date de crea :</strong><?php echo $todo_item['created']; ?></p>
<p><strong>date de modif :</strong><?php echo $todo_item['modified']; ?></p>
<p><?php echo $html->link(array('action' => 'index'), 'retour au listing'); ?></p>
