<table class="odd">
	<caption>Affichage de la table <?php echo $table_name; ?></caption>
	<thead>
		<tr>
		<?php
		foreach ($struct_table as $field)
		    echo '<td>' . $field['Field'] . '</td>';
		?>
			<td colspan="2">Action</td>
		</tr>
	</thead>
	<tfoot>
		<tr><td colspan="<?php echo count($struct_table) + 1; ?>">
		    <?php echo $html->link(array('controller' => 'row', 'action' => 'create', 'params' => array('table_selected' => $table_name)), 'Inserer') ?></td>
		    </tr>
	</tfoot>
	<tbody>
		<?php foreach ($content_table as $table): ?>
		<tr>
		    <?php foreach($table as $content): ?>
    	    <td><?php echo $content; ?></td>
    	    <?php endforeach;?>
    	    <td><?php echo  $html->link(array('controller' => 'row', 'action' => 'update', 'params' => $form->getPrimaryKeys($struct_table, $table)), 'Editer'); ?></td>
    	    <td><?php echo $html->link(array('controller' => 'row', 'action' => 'delete', 'params' => $form->getPrimaryKeys($struct_table, $table)), 'Supprimer'); ?></td>
	       </tr>
		<?php endforeach; ?>
	</tbody>
</table>