<?php 
if (isset($db_selected))
    echo $html->render_element('menu_db', array('db_selected' => $db_selected));
?>
<table class="odd">
	<caption>Table dans la base de donnée <?php echo $db_name ?></caption>
	<thead>
		<tr>
			<th>Table</th>
			<th colspan="7">Actions</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="8"><?php echo $html->link(array('controller' => 'table',
														 'action' => 'create',
													     'params' => array('db_selected' => $db_selected)),
												   'Creer une table',
			                                       array('onclick' => "doRequest('table', 'create', 'db_selected', '" . $db_selected . "');")); ?></td>
		</tr>
	</tfoot>
	<tbody>
	<?php foreach ($db_tables as $table_name => $table_struct): ?>
		<tr>
			<td><?php echo $table_name ?></td>
			<td><?php echo $html->link(array('controller' => 'table',
											 'action' => 'list',
											 'params' => array('table_selected' => $table_selected)),
									  'Afficher',
			                          array('onclick' => "doRequest('table', 'list', 'table_selected', '" . $table_selected . "');")); ?></td>
			<td><?php echo $html->link(array('controller' => 'table',
											 'action' => 'struct',
											 'params' => array('table_selected' => $table_selected)),
									  'Structure',
			                          array('onclick' => "doRequest('table', 'struct', 'table_selected', '". $table_selected . "');")); ?></td>
			<td><?php echo $html->link(array('controller' => 'table', 'action' => 'search', 'params' => array('table_selected' => $table_selected)), 'Rechercher'); ?></td>
			<td><?php echo $html->link(array('controller' => 'row',
			                          		 'action' => 'create',
			                          		 'params' => array('table_selected' => $table_selected)),
			                          'Inserer',
			                          array('onclick' => "doRequest('row', 'create', 'table_selected', '". $table_selected . "');")); ?></td>
			<td><?php echo $html->link(array('controller' => 'table', 'action' => 'export', 'params' => array('table_selected' => $table_selected)), 'Exporter'); ?></td>
			<td><?php echo $html->link(array('controller' => 'table', 'action' => 'truncate', 'params' => array('table_selected' => $table_selected)), 'Vider'); ?></td>
			<td><?php echo $html->link(array('controller' => 'table', 'action' => 'drop', 'params' => array('table_selected' => $table_selected)), 'Supprimer'); ?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
