<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php echo $page_title; ?></title>
		<script type="text/javascript">
			var relative_root = "<?php echo $relative_root ?>";
		</script>
		<!-- IMPORT DES CSS COMMUNS -->
		<?php echo $html->css('common'); ?>
		
		<!-- IMPORT DES JS COMMUNS -->
		<?php echo $html->js('lib/Ajax'); ?>
		<?php echo $html->js('lib/Effect'); ?>
		<?php echo $html->js('lib/Element'); ?>
		<?php echo $html->js('lib/Event'); ?>
		<?php echo $html->js('lib/Validator'); ?>
        <?php echo $html->js('main'); ?>
        <script type="text/javascript">
        	function doRequest(argv)
        	{
                request = new Ajax();
            	action = "";
            	controller = "";
            	key_value_vars = "";
            	for (param in argv)
            	{
                	if (param == 'controller')
                		controller = argv.controller;
                	else if (param == 'action')
                		action = argv.action;
                	else if (param == 'complete')
                	{
                		if ($(argv.complete) == null)
                			Ajax.prototype.completeElement = null;
                		else
                        	Ajax.prototype.completeElement = $(argv.complete);
                	}
                	else
                		key_value_vars = key_value_vars + "" + param + "=" + argv[param] + "&";
            	}
                url = "/" + relative_root + "/" + controller + "/" + "__ajax_" + action + "?" + key_value_vars;
                while (url.charAt(url.length- 1) == "?" || url.charAt(url.length - 1) == "&")
            		url = url.substring(0, (url.length - 1));
            	request.doRequest("get", url, null);
            	return (false);
        	}
            function addField(event)
        	{
        		element = event.currentTarget.parentNode.parentNode.parentNode.parentNode.rows[1].cloneNode(true);
        		event.currentTarget.parentNode.parentNode.parentNode.parentNode.lastChild.previousSibling.appendChild(element);
        	}
        	function validateField(event)
        	{
        		alert("validateField");
        		return (true);
        	}
		</script>
    </head>
	<body onload="DocumentLoad(event);">
		<div id="header">
			<h1>{ETNA - PhpMyAdmin}</h1>
			<p class="svn">svn/wiki: <a href="http://code.google.com/p/etna-1-pma/">http://code.google.com/p/etna-1-pma/</a></p>
			<p class="copyright">authors : fourca_m & borrel_a</p>
		</div>
		<div id="main_menu" class="bordered">
			<h3 class="breadcrumb">databases</h3>
            <?php
            echo '<ul class="menu_tab" id="databases_menu">';
    		foreach ($databases as $database)
    		{
    		    $options = array();
    		    if (isset($db_selected) && $db_selected == $database['Database'])
    		    {
    		        $options['selected'] = "selected";
    		        echo '<li>' . $html->link(array('controller' => 'db',
    		        								'action' => 'list',
    		        								'params' => array('db_selected' => $database['Database'])),
    		                             substr($database['Database'], 0, 18) . (strlen($database['Database']) > 18 ? '...' : ''),
    		                             array('title' => 'bdd: ' . $database['Database']));
                    if (isset($tables))
                    {
                        echo '<ul class="menu_tab" id="tables_menu">';
                        foreach ($tables as $table_name => $struct)
                        {
                            echo '<li>' . $html->link(array('controller' => 'table', 
                            								'action' => 'struct',
                            								'params' => array('table_selected' => $table_name)),
                                                     substr($table_name, 0, 18) . (strlen($table_name) > 18 ? '...' : ''),
                                                     array('title' => 'table: ' . $table_name)) . '</li>';
                        }
                        echo '</ul>';
                    }
                    echo '</li>';
    		    }
    		    else
    		    {
    		        echo '<li>' . $html->link(array('controller' => 'db',
    		        								'action' => 'list',
    		        								'params' => array('db_selected' => $database['Database'])),
    		                      $database['Database'],
    		                      array('title' => 'bdd: ' . $database['Database'])) . '</li>';
    		    }
    		}
    		echo '</ul>';
            ?>
        </div>
    	<?php echo $action_content; ?>
	</body>
</html>