<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php echo $page_title; ?></title>
		<script type="text/javascript">
			var relative_root = "<?php echo $relative_root ?>";
		</script>
		<!-- IMPORT DES CSS COMMUNS -->
		<?php echo $html->css('common'); ?>
		
		<!-- IMPORT DES JS COMMUNS -->
		<?php echo $html->js('lib/Ajax'); ?>
		<?php echo $html->js('lib/Effect'); ?>
		<?php echo $html->js('lib/Element'); ?>
		<?php echo $html->js('lib/Event'); ?>
        <?php echo $html->js('main'); ?>
	</head>
	<body onload="DocumentLoad(event);">
		<div id="main_menu" class="bordered">
			<h3>Bases</h3>
            <?php
            echo '<ul class="menu_tab" id="databases_menu">';
    		foreach ($databases as $database)
    		{
    		    $options = array();
    		    if ($db_selected == $database['Database'])
    		    {
    		        $options['selected'] = "selected";
    		        echo '<li>' . $html->link(array('controller' => 'db',
    		        								'action' => 'list',
    		        								'params' => array('db_selected' => $database['Database'])),
    		                             substr($database['Database'], 0, 18) . (strlen($database['Database']) > 18 ? '...' : ''),
    		                             array('title' => 'bdd: ' . $database['Database']));
                    if (isset($tables))
                    {
                        echo '<ul class="menu_tab" id="tables_menu">';
                        foreach ($tables as $table_name => $struct)
                        {
                            echo '<li>' . $html->link(array('controller' => 'table', 
                            								'action' => 'struct',
                            								'params' => array('table_selected' => $table_name)),
                                                     substr($table_name, 0, 18) . (strlen($table_name) > 18 ? '...' : ''),
                                                     array('title' => 'table: ' . $table_name)) . '</li>';
                        }
                        echo '</ul>';
                    }
                    echo '</li>';
    		    }
    		    else
    		    {
    		        echo '<li>' . $html->link(array('controller' => 'db',
    		        								'action' => 'list',
    		        								'params' => array('db_selected' => $database['Database'])),
    		                      $database['Database'],
    		                      array('title' => 'bdd: ' . $database['Database'])) . '</li>';
    		    }
    		}
    		echo '</ul>';
            ?>
        </div>
        <div id="content" class="bordered">
        	<?php 
            if (isset($table_selected) && $table_name == $table_selected)
            {
                echo '<ul>' .
                        '<li>' . $html->link(array('controller' => ''), "") . '</li>' .
                        '<li>' . $html->link(array('controller' => 'table', 'action' => 'list', 'params' => array('table_selected' => $table_selected)), 'Afficher') . '</li>' .
                        '<li>' . $html->link(array('controller' => 'row', 'action' => 'create', 'params' => array('table_selected' => $table_selected)), 'Inserer') . '</li>' .
                     '</ul>';
            }
        	echo $action_content;
        	?>
		</div>
	</body>
</html>