<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php echo $page_title; ?></title>
		<script type="text/javascript">
			var relative_root = "<?php echo $relative_root ?>";
		</script>
		<!-- IMPORT DES CSS COMMUNS -->
		<?php echo $html->css('common'); ?>
		
		<!-- IMPORT DES JS COMMUNS -->
		<?php echo $html->js('lib/Ajax'); ?>
		<?php echo $html->js('lib/Effect'); ?>
		<?php echo $html->js('lib/Element'); ?>
		<?php echo $html->js('lib/Event'); ?>
        <?php echo $html->js('dbMenu'); ?>
	</head>
	<body onload="DocumentLoad(event);">
		<div id="main_menu">
    		<form onchange="menuHandler(event);">
            	<p><label>BDD :</label> 
                	<select id ="db_selector">
            		<?php
            		foreach ($databases as $database)
            		{
            		    $selected = ($db_selected == $database['Database'] ? 'selected="' . $database['Database'] . '"' : null);
            			echo '<option 
            					value="' . $database['Database'] . '"' . 
            					$selected . '>' .
            			            $database['Database'] .
            			     	'</option>';
            		}
            		?>
                	</select>
            	</p>
            </form>
        	<!-- BLOCK MENU -->
            <?php /*if (isset($db_selected)): ?>
            <ul class="menu_tab">
            	<li><?php echo $db_selected; ?></li>
            	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'list'), 'List'); ?></li>
            	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'visualization'), 'visualisation'); ?></li>
            	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'export'), 'exporter'); ?></li>
            	<li><?php echo $html->link(array('controller' => 'db', 'action' => 'import'), 'importer'); ?></li>
            </ul>
            <?php endif;*/ ?>
                        		
            <?php
            if (isset($tables))
            {
                echo '<ul class="menu_tab">' . 
                		'<li>' . $html->link(array('controller' => 'db', 'action' => 'list', 'params' => array('db_selected' => $db_selected)), $db_selected). '</li>' .
                        '<ul>';
                foreach ($tables as $table_name => $struct)
                {
                    echo '<li>' . $html->link(array('controller' => 'table', 'action' => 'struct', 'params' => array('table_selected' => $table_name)), $table_name) . '</li>';
                }
                echo 	'</ul>'.
                	 '</ul>';
               
            }
            ?>
        </div>
        <div id="content">
        	<?php 
            if (isset($table_selected) && $table_name == $table_selected)
            {
                echo '<ul>' .
                        '<li>' . $html->link(array('controller' => ''), "") . '</li>' .
                        '<li>' . $html->link(array('controller' => 'table', 'action' => 'list', 'params' => array('table_selected' => $table_selected)), 'Afficher') . '</li>' .
                        '<li>' . $html->link(array('controller' => 'row', 'action' => 'create', 'params' => array('table_selected' => $table_selected)), 'Inserer') . '</li>' .
                     '</ul>';
            }
        	echo $action_content;
        	?>
		</div>
	</body>
</html>