<h3>TODO</h3>
<ul>
	<li>Gerer l'interface de connexion</li>
	<li>Implementer IDAO sur le model</li>
	<li>Implementer des drivers de connexion</li>
	<li>Gerer les logs SQL (requetes)</li>
	<li>Mettre en cache la structure de la bdd</li>
	<li>Gerer l'i18n</li>
	<li>Gerer l'appel de fonction __ajax_</li>
	<li>Crossbrowser pour la lib js</li>
	<li>Revoir l'implementation du visuel</li>
	<li>hide/show databases</li>
</ul>